#theme = "catppuccin_mocha"
theme = "github_dark"


[editor]
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
q = ":wq"
Q = ":q!"
C-q = ":wq"
C-l = "file_picker"
A-q = ":q!"
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"
# y = ":clipboard-yank-join"
# Y = ":clipboard-yank"
# R = ":clipboard-paste-replace"
# d = [":clipboard-yank-join", "delete_selection"]
S-d = ["evil_characterwise_select_mode", "goto_line_end", "evil_delete"]

[keys.select]
p = ":clipboard-paste-after"
P = ":clipboard-paste-before"
# y = ":clipboard-yank-join"
# Y = ":clipboard-yank"
# R = ":clipboard-paste-replace"
# d = [":clipboard-yank-join", "delete_selection"]
S-d = "evil_delete"

